### PR TITLE
update to V5.0.0

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@izahn, I don't have much of use to offer on this feedstock.  I'm going to remove myself as a maintainer and rerender.  I hope you don't mind.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by izahn** [comment]
> @izahn, I don't have much of use to offer on this feedstock. I'm going to remove myself as a maintainer and rerender. I hope you don't mind.

Thanks for everything @xylar we'll try to take good care of it!

**Comment by izahn** [comment]
@conda-forge/tesseract according to https://github.com/tesseract-ocr/tesseract/issues/3271#issuecomment-770629665 `training-tools` cannot be built on windows without SW so I've disabled building `training-tools` for windows. If anyone thinks this is a bad idea please let me know, otherwise I'll merge this in a day or two.

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Pull request merged**
