### PR TITLE
Feature/fix missing tessdata

### PR DESCRIPTION
**Pull request by abloemert**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR adds missing tessdata for the Windows package. By storing the data in a generic folder, it will be possible to create a separate (noarch) package for tessdata in the future.

### CODE REVIEW

**Comment by abloemert** [comment]
@conda-forge-admin, please rerender

**Comment by izahn** [comment]
This looks good to me, any concerns about merging it @conda-forge/tesseract ?

**Comment by xylar** [comment]
I'm not really expert enough to say but fine by me...

**Comment by izahn** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
