### PR TITLE
rebuild for openjpeg25

### LINKED ISSUE #42: Rerender for openjpeg25
### Additional comment:

@conda-forge-admin please rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

Closes #42.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Hmm this needs unpinning for windows : https://github.com/conda-forge/leptonica-feedstock

**Comment by hmaarrfk** [comment]
Maybe you just need to create a 1.80 leptonica branch while you resolve this :/

**Comment by izahn** [comment]
Or just drop windows support, which I'm inclined to do instead.

**Comment by hmaarrfk** [comment]
I guess the solution is between you and the other maintainers

**Pull request merged**
