### PR TITLE
Removed leptonica restrictions on Win

### PR DESCRIPTION
**Pull request by joseavegaa**
Removed leptonica version restriction on Windows, as the newest version available on conda-forge is 1.82.0 for Windows, and should be supported by tesseract if compiled with it.

`@ conda-forge-admin, please render`

### CODE REVIEW

**Comment by izahn** [comment]
Thanks for working on this! Leptonica is pinned on Windows just because I couldn't get it working with the latest Leptonica build. See https://github.com/conda-forge/tesseract-feedstock/pull/30 and https://github.com/conda-forge/tesseract-feedstock/pull/31 for some history.

If you can get it working that will be great!

**Comment by joseavegaa** [comment]
Thanks! I’ve been trying to build it using the automated pipeline, but haven’t quite get it working just yet. 

I’ll try to make it work consistently on all platforms, and then I’ll mark this PR as ready for review.

**Comment by joseavegaa** [comment]
@conda-forge-admin, please rerender

**Comment by joseavegaa** [comment]
@conda-forge-admin, please rerender

**Comment by joseavegaa** [comment]
@conda-forge-admin, please rerender

**Comment by pkgw** [comment]
This was rolled up into #50.

**Pull request closed without merging**
