### PR TITLE
Add missing dependencies

### PR DESCRIPTION
**Pull request by CurtLH**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Can you rerender `leptonica` and bump the build number? After that is merged, restart this PR

**Comment by CurtLH** [comment]
@conda-forge-admin, please rerender

**Comment by CurtLH** [comment]
@isuruf -- I followed you guidance and [rerender `leptonica`](https://github.com/conda-forge/leptonica-feedstock/pull/4) and then rereendered and trigger `tesseract`, but the same issue is present.

```bash
+ tesseract --help
tesseract: error while loading shared libraries: libwebp.so.7: cannot open shared object file: No such file or directory
Tests failed for tesseract-3.05.01-h1ccaaf6_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for tesseract-3.05.01-h1ccaaf6_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
removing: tesseract-3.05.01-h1ccaaf6_1.tar.bz2
TESTS FAILED: tesseract-3.05.01-h1ccaaf6_1.tar.bz2
Exited with code 1
```

**Comment by CurtLH** [comment]
I'm closing the PR to completely start over.

**Pull request closed without merging**
